/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.DanhMuc;
import Model.NhaXuatBan;
import Model.Sach;
import Model.TacGia;
import Services.NhaXuatBanServices;
import Services.TacGiaServices;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author congt
 */
public class CapNhatNhaXuatBan extends javax.swing.JFrame {

    /**
     * Creates new form CapNhatNhaXuatBan
     */
    int count = 1;
    NhaXuatBanServices nxbServices;
    NhaXuatBan nxb;
    DefaultTableModel defaultTableModle;
    
    public CapNhatNhaXuatBan() {
        try {
            nxbServices = new NhaXuatBanServices();
            initComponents();
            
            defaultTableModle = new DefaultTableModel(){
                @Override
                public boolean isCellEditable(int row, int column){
                    return false;
                }
            };
            tableNhaXuatBan.setModel(defaultTableModle);
            
            defaultTableModle.addColumn("Id");
            defaultTableModle.addColumn("Mã NXB");
            defaultTableModle.addColumn("Tên Nhà Xuất Bản");
            defaultTableModle.addColumn("Địa Chỉ");
            defaultTableModle.addColumn("Điện Thoại");

            List<NhaXuatBan> nxbList = nxbServices.getAllNXB();
            for (NhaXuatBan nxb:nxbList){
                defaultTableModle.addRow(new Object[]{count++,nxb.getMaNXB(),nxb.getTenNXB(),nxb.getDiaChiNXB(),nxb.getDienThoai()});
            }
            // đếm
            jTFCount.setText("");
            int count = tableNhaXuatBan.getRowCount();
            jTFCount.setText("" + count);
        } catch (SQLException ex) {
            Logger.getLogger(CapNhatNhaXuatBan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFTenNXB = new javax.swing.JTextField();
        jTFDiaChi = new javax.swing.JTextField();
        jTFDienThoai = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNhaXuatBan = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTFCount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cập Nhật Nhà Xuất Bản");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cập Nhật Nhà Xuất Bản");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tên Nhà Xuất Bản");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Địa Chỉ Nhà Xuất Bản");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Điện Thoại");

        jTFTenNXB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFTenNXB.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTFDiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFDiaChi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDiaChiActionPerformed(evt);
            }
        });

        jTFDienThoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFDienThoai.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\congt\\OneDrive\\Documents\\NetBeansProjects\\QuanLyBanSach\\build\\classes\\Images\\Add.png")); // NOI18N
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\congt\\OneDrive\\Documents\\NetBeansProjects\\QuanLyBanSach\\build\\classes\\Images\\Exit.png")); // NOI18N
        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tableNhaXuatBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableNhaXuatBan);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\congt\\OneDrive\\Documents\\NetBeansProjects\\QuanLyBanSach\\build\\classes\\Images\\Refresh.png")); // NOI18N
        jButton3.setText("Làm Mới");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\congt\\OneDrive\\Documents\\NetBeansProjects\\QuanLyBanSach\\build\\classes\\Images\\Edit.png")); // NOI18N
        jButton4.setText("Sửa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTFCount.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTFCount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFCount.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Tổng Số");

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\congt\\OneDrive\\Documents\\NetBeansProjects\\QuanLyBanSach\\build\\classes\\Images\\Delete.png")); // NOI18N
        jButton5.setText("Xóa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFTenNXB)
                            .addComponent(jTFDiaChi)
                            .addComponent(jTFDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(30, 30, 30)
                        .addComponent(jButton5)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTFCount, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTFTenNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTFDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addGap(26, 26, 26)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDiaChiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // random maTG
        int code = 0;
        String strCode = "";
        code = (int) Math.floor(((Math.random() * 899999) + 100000));
        strCode = String.valueOf(code);
        //
        if (jTFTenNXB.getText().equals("") || jTFDiaChi.getText().equals("") || jTFDienThoai.getText().equals("")){
            JOptionPane.showMessageDialog(CapNhatNhaXuatBan.this, "Không Nhận Giá Trị Rỗng","Lỗi",JOptionPane.ERROR_MESSAGE);
        }
        else{
        int confirm = JOptionPane.showConfirmDialog(CapNhatNhaXuatBan.this, "Bạn Có Chắc Chắn Muốn Thêm Không!","Thông Báo",JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION){
                try {
                    try {
                        nxb = new NhaXuatBan();
                        nxbServices = new NhaXuatBanServices();
                        nxb.setMaNXB(strCode);
                        nxb.setTenNXB(jTFTenNXB.getText().trim());
                        nxb.setDiaChiNXB(jTFDiaChi.getText().trim());
                        nxb.setDienThoai(jTFDienThoai.getText().trim());
                        
                        nxbServices.addNXB(nxb);
                    } catch (SQLException ex) {
                        Logger.getLogger(Category.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    // cập nhật lại table và đếm lại
                    jTFTenNXB.setText("");
                    jTFDiaChi.setText("");
                    jTFDienThoai.setText("");
                    count = 1;
                    
                    defaultTableModle.setRowCount(0);
                    List<NhaXuatBan> nxbList = nxbServices.getAllNXB();
                    for (NhaXuatBan nxb:nxbList){
                        defaultTableModle.addRow(new Object[]{count++,nxb.getMaNXB(),nxb.getTenNXB(),nxb.getDiaChiNXB(),nxb.getDienThoai()});
                    }
                    //  đếm lại
                    jTFCount.setText("");
                    jTFCount.setText("" + tableNhaXuatBan.getRowCount());
                } catch (SQLException ex) {
                    Logger.getLogger(Category.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int row = tableNhaXuatBan.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(CapNhatNhaXuatBan.this,"Vui Lòng Chọn 1 Hàng Cần Sửa!","Lỗi",JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            int id = Integer.valueOf(String.valueOf(tableNhaXuatBan.getValueAt(row,1)));
            new EditNhaXuatBan(id).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            count = 1;
            //
            jTFTenNXB.setText("");
            jTFDiaChi.setText("");
            jTFDienThoai.setText("");
            // làm mới table
            defaultTableModle.setRowCount(0);
            List<NhaXuatBan> nxbList = nxbServices.getAllNXB();
            for (NhaXuatBan nxb:nxbList){
                defaultTableModle.addRow(new Object[]{count++,nxb.getMaNXB(),nxb.getTenNXB(),nxb.getDiaChiNXB(),nxb.getDienThoai()});
            }
            // đếm
            jTFCount.setText("");
            int count = tableNhaXuatBan.getRowCount();
            jTFCount.setText("" + count);
        } catch (SQLException ex) {
            Logger.getLogger(CapNhatNhaXuatBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Products().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int row = tableNhaXuatBan.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(CapNhatNhaXuatBan.this, "Vui Lòng Chọn 1 Hàng Để Xóa","Lỗi",JOptionPane.ERROR_MESSAGE);
        } else{
            int confirm = JOptionPane.showConfirmDialog(CapNhatNhaXuatBan.this, "Bạn Chắc Chắn Muốn Xóa Không!","Thông Báo",JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION){
                int id = Integer.valueOf(String.valueOf(tableNhaXuatBan.getValueAt(row,1)));

                try {
                    nxbServices.deleteNXB(id);
                } catch (SQLException ex) {
                    Logger.getLogger(Category.class.getName()).log(Level.SEVERE, null, ex);
                }
                // lam moi
                try {
                    defaultTableModle.setRowCount(0);
                    List<NhaXuatBan> nxbList = nxbServices.getAllNXB();
                    int countDelete = 1;
                    for (NhaXuatBan nxb:nxbList){
                        defaultTableModle.addRow(new Object[]{countDelete++, nxb.getMaNXB(),nxb.getTenNXB(),nxb.getDiaChiNXB(),nxb.getDienThoai()});
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Category.class.getName()).log(Level.SEVERE, null, ex);
                }
                // đếm số lượng
                int count11 = 0;
                count11 = tableNhaXuatBan.getRowCount();
                jTFCount.setText("");
                jTFCount.setText(Integer.toString(count11));
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCount;
    private javax.swing.JTextField jTFDiaChi;
    private javax.swing.JTextField jTFDienThoai;
    private javax.swing.JTextField jTFTenNXB;
    private javax.swing.JTable tableNhaXuatBan;
    // End of variables declaration//GEN-END:variables
}
