/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.NhaXuatBan;
import Services.NhaXuatBanServices;
import Services.TacGiaServices;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author congt
 */
public class EditNhaXuatBan extends javax.swing.JFrame {

    /**
     * Creates new form EditNhaXuatBan
     */
    NhaXuatBan nxb;
    NhaXuatBanServices nxbServices;
    
    public EditNhaXuatBan(int id) {
        try {
            nxbServices = new NhaXuatBanServices();
            initComponents();
            
            nxb = nxbServices.getNXBById(id);
            
            jTFMaNXB.setText(nxb.getMaNXB());
            jTFTenNXB.setText(nxb.getTenNXB());
            jTFDiaChi.setText(nxb.getDiaChiNXB());
            jTFDienThoai.setText(nxb.getDienThoai());
        } catch (SQLException ex) {
            Logger.getLogger(EditNhaXuatBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFMaNXB = new javax.swing.JTextField();
        jTFTenNXB = new javax.swing.JTextField();
        jTFDiaChi = new javax.swing.JTextField();
        jTFDienThoai = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cập Nhật Nhà Xuất Bản");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã Nhà Xuất Bản");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tên Nhà Xuất Bản");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Địa Chỉ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Điện Thoại");

        jTFMaNXB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFMaNXB.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFMaNXB.setEnabled(false);
        jTFMaNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFMaNXBActionPerformed(evt);
            }
        });

        jTFTenNXB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFTenNXB.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFTenNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTenNXBActionPerformed(evt);
            }
        });

        jTFDiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFDiaChi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDiaChiActionPerformed(evt);
            }
        });

        jTFDienThoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFDienThoai.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTFDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addComponent(jTFDiaChi)
                                .addComponent(jTFTenNXB)
                                .addComponent(jTFMaNXB)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFTenNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFTenNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTenNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTenNXBActionPerformed

    private void jTFDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDiaChiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Products().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTFTenNXB.setText("");
        jTFDiaChi.setText("");
        jTFDienThoai.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTFMaNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFMaNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFMaNXBActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jTFTenNXB.getText().equals("") || jTFDiaChi.getText().equals("") || jTFDienThoai.getText().equals("")){
            JOptionPane.showMessageDialog(EditNhaXuatBan.this, "Không Nhận Giá Trị Rỗng","Lỗi",JOptionPane.ERROR_MESSAGE);
        }
        else{
            int confirm = JOptionPane.showConfirmDialog(EditNhaXuatBan.this, "Bạn Có Chắc Muốn Thay Đổi Không!","Thông Báo",JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION){
                try {
                    nxb.setMaNXB(jTFMaNXB.getText().trim());
                    nxb.setTenNXB(jTFTenNXB.getText().trim());
                    nxb.setDiaChiNXB(jTFDiaChi.getText().trim());
                    nxb.setDienThoai(jTFDienThoai.getText().trim());

                    nxbServices.update(nxb);
                    new CapNhatNhaXuatBan().setVisible(true);
                    this.dispose();
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(EditDanhMuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTFDiaChi;
    private javax.swing.JTextField jTFDienThoai;
    private javax.swing.JTextField jTFMaNXB;
    private javax.swing.JTextField jTFTenNXB;
    // End of variables declaration//GEN-END:variables
}
