/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.HoaDonThongKe;
import Services.HoaDonThongKeServices;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author congt
 */
public class ThongKeSanPham extends javax.swing.JFrame {

    /**
     * Creates new form ThongKeSanPham
     */
    DefaultTableModel defaultTableModle;
    HoaDonThongKeServices tkServices;
    HoaDonThongKe hdTK  = new HoaDonThongKe();
    
    public ThongKeSanPham() throws SQLException {
        
        tkServices = new HoaDonThongKeServices();
        initComponents();
        
        // add vao combobox
        for(int i =2; i<=10; i++){
            cbTopSP.addItem(String.valueOf(i));
        }
        //
        int top = Integer.parseInt(cbTopSP.getSelectedItem().toString());
        //
        defaultTableModle = new DefaultTableModel(){
                @Override
                public boolean isCellEditable(int row, int column){
                    return false;
                }
            };
            tblTKSP.setModel(defaultTableModle);
            
            defaultTableModle.addColumn("Mã Sách");
            defaultTableModle.addColumn("Tên Sách");
            defaultTableModle.addColumn("Giá");
            defaultTableModle.addColumn("Số Lượng Bán");
            
            List<HoaDonThongKe> hdList = tkServices.getAllThongKeTopBanChay(top);
            for (HoaDonThongKe hd:hdList){
                defaultTableModle.addRow(new Object[]{hd.getMaSach(),hd.getTenSach(),hd.getGiaBan(),hd.getSoLuongBan()});
            }
            
            // đếm
            jTFCount.setText("");
            int count = tblTKSP.getRowCount();
            jTFCount.setText("" + count);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFCount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTKSP = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbTopSP = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thống Kê Sản Phẩm");

        jTFCount.setEditable(false);
        jTFCount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTFCount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFCount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTFCount.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("THỐNG KÊ SẢN PHẨM BÁN CHẠY");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Chọn TOP mấy sản phẩm bán chạy");

        tblTKSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTKSP);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\congt\\OneDrive\\Documents\\NetBeansProjects\\QuanLyBanSach\\build\\classes\\Images\\Search.png")); // NOI18N
        jButton1.setText("Thống Kê");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Tổng Số");

        cbTopSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbTopSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTopSPActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\congt\\OneDrive\\Documents\\NetBeansProjects\\QuanLyBanSach\\build\\classes\\Images\\Home.png")); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFCount, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(49, 49, 49)
                        .addComponent(cbTopSP, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(290, 290, 290))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbTopSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int top = Integer.parseInt(cbTopSP.getSelectedItem().toString());    
        defaultTableModle.setRowCount(0);
        try {
            List<HoaDonThongKe> hdList = tkServices.getAllThongKeTopBanChay(top);
            for (HoaDonThongKe hd:hdList){
                defaultTableModle.addRow(new Object[]{hd.getMaSach(),hd.getTenSach(),hd.getGiaBan(),hd.getSoLuongBan()});
            }
        } catch (SQLException ex) {
            Logger.getLogger(ThongKeSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
        // đếm
        jTFCount.setText("");
        jTFCount.setText("" + defaultTableModle.getRowCount());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbTopSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTopSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTopSPActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new ThongKe().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbTopSP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCount;
    private javax.swing.JTable tblTKSP;
    // End of variables declaration//GEN-END:variables
}
